"""create modernization_recommendations table

Revision ID: 1f4b4eb645db
Revises: 50102818d27b
Create Date: 2026-08-21 11:27:33.454141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1f4b4eb645db'
down_revision: Union[str, Sequence[str], None] = '50102818d27b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modernization_recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('modernization_case_id', sa.Uuid(), nullable=False),
    sa.Column('complexity_score', sa.Integer(), nullable=False),
    sa.Column('risk_signals', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('matched_option_ids', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('narrative', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=False),
    sa.Column('citations', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application_profiles.id'], ),
    sa.ForeignKeyConstraint(['modernization_case_id'], ['modernization_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modernization_recommendations_application_id'), 'modernization_recommendations', ['application_id'], unique=False)
    op.create_index(op.f('ix_modernization_recommendations_modernization_case_id'), 'modernization_recommendations', ['modernization_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modernization_recommendations_modernization_case_id'), table_name='modernization_recommendations')
    op.drop_index(op.f('ix_modernization_recommendations_application_id'), table_name='modernization_recommendations')
    op.drop_table('modernization_recommendations')
    # ### end Alembic commands ###
