"""create diagram_metadata table

Revision ID: 385522fad795
Revises: fe430ddb02ed
Create Date: 2026-08-21 16:39:59.589488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '385522fad795'
down_revision: Union[str, Sequence[str], None] = 'fe430ddb02ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagram_metadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('linked_decision_ids', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diagram_metadata')
    # ### end Alembic commands ###
