"""create generated_test_suites table

Revision ID: 46c3da47993c
Revises: 4bb9f987d1a1
Create Date: 2026-08-21 15:28:21.988852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '46c3da47993c'
down_revision: Union[str, Sequence[str], None] = '4bb9f987d1a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_test_suites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_snippet', sa.Text(), nullable=False),
    sa.Column('generated_tests', sa.Text(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generated_test_suites')
    # ### end Alembic commands ###
