"""create code_review_runs table

Revision ID: 4bb9f987d1a1
Revises: 1f4b4eb645db
Create Date: 2026-08-21 14:48:14.709205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4bb9f987d1a1'
down_revision: Union[str, Sequence[str], None] = '1f4b4eb645db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_review_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_snippet', sa.Text(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('findings', sa.Text(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('citations', sa.Text(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('code_review_runs')
    # ### end Alembic commands ###
