"""create modernization_cases table

Revision ID: 50102818d27b
Revises: f87263eef27b
Create Date: 2026-08-21 11:14:21.229848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '50102818d27b'
down_revision: Union[str, Sequence[str], None] = 'f87263eef27b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modernization_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('technology_stack', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('hosting', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('release_process', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('scale', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('pain_points', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modernization_cases_application_id'), 'modernization_cases', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modernization_cases_application_id'), table_name='modernization_cases')
    op.drop_table('modernization_cases')
    # ### end Alembic commands ###
