"""create documentation_drafts table

Revision ID: 99f0090d859c
Revises: 46c3da47993c
Create Date: 2026-08-21 15:54:59.675986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '99f0090d859c'
down_revision: Union[str, Sequence[str], None] = '46c3da47993c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentation_drafts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_snippet', sa.Text(), nullable=False),
    sa.Column('draft_text', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentation_drafts')
    # ### end Alembic commands ###
