"""create approval_decisions table

Revision ID: f87263eef27b
Revises: e00cf14dc933
Create Date: 2026-08-20 18:56:47.339620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f87263eef27b'
down_revision: Union[str, Sequence[str], None] = 'e00cf14dc933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('correlation_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_decisions_entity_id'), 'approval_decisions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_approval_decisions_entity_type'), 'approval_decisions', ['entity_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_decisions_entity_type'), table_name='approval_decisions')
    op.drop_index(op.f('ix_approval_decisions_entity_id'), table_name='approval_decisions')
    op.drop_table('approval_decisions')
    # ### end Alembic commands ###
