"""create agent_definitions and agent_versions tables

Revision ID: faeff391d955
Revises: 385522fad795
Create Date: 2026-08-24 09:33:09.747763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'faeff391d955'
down_revision: Union[str, Sequence[str], None] = '385522fad795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('owner', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('security_tier', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('lifecycle_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_definitions_name'), 'agent_definitions', ['name'], unique=True)
    op.create_table('agent_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('input_schema', sa.Text(), nullable=False),
    sa.Column('output_schema', sa.Text(), nullable=False),
    sa.Column('allowed_tools', sa.Text(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_versions_agent_id'), 'agent_versions', ['agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_versions_agent_id'), table_name='agent_versions')
    op.drop_table('agent_versions')
    op.drop_index(op.f('ix_agent_definitions_name'), table_name='agent_definitions')
    op.drop_table('agent_definitions')
    # ### end Alembic commands ###
