"""create architecture_decisions and architecture_reviews tables

Revision ID: fe430ddb02ed
Revises: 99f0090d859c
Create Date: 2026-08-21 16:21:52.476000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fe430ddb02ed'
down_revision: Union[str, Sequence[str], None] = '99f0090d859c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('architecture_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('drivers', sa.Text(), nullable=False),
    sa.Column('alternatives', sa.Text(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('consequences', sa.Text(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('architecture_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.Column('business_alignment', sa.Integer(), nullable=False),
    sa.Column('security', sa.Integer(), nullable=False),
    sa.Column('privacy', sa.Integer(), nullable=False),
    sa.Column('reliability', sa.Integer(), nullable=False),
    sa.Column('performance', sa.Integer(), nullable=False),
    sa.Column('testability', sa.Integer(), nullable=False),
    sa.Column('operability', sa.Integer(), nullable=False),
    sa.Column('integration', sa.Integer(), nullable=False),
    sa.Column('data', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['architecture_decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_architecture_reviews_decision_id'), 'architecture_reviews', ['decision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_architecture_reviews_decision_id'), table_name='architecture_reviews')
    op.drop_table('architecture_reviews')
    op.drop_table('architecture_decisions')
    # ### end Alembic commands ###
